# Generated by Django 5.1.6 on 2026-06-15 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('R', 'Restaurante'), ('P', 'Pizzaria'), ('H', 'Hamburgueria'), ('F', 'Food Truck')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.estabelecimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.user')),
            ],
        ),
        migrations.DeleteModel(
            name='estabelecimentos',
        ),
    ]
